/**
 * Root.tsx — AUTO-GENERATED by OverlayTool.
 * Explicit imports for all compositions (works with any bundler).
 * Re-generated on each render to pick up new templates.
 *
 * Duration override: pass _durationFrames in props to override
 * the composition's default durationInFrames.
 */

import React from 'react';
import { Composition } from 'remotion';

import { compositionConfig as CaptionOverlayConfig, CaptionOverlay } from './CaptionOverlay';
import { compositionConfig as GlassSplitConfig, GlassSplit } from './GlassSplit';
import { compositionConfig as SplitLayoutConfig, SplitLayout } from './SplitLayout';
import { compositionConfig as TitleOverlayConfig, TitleOverlay } from './TitleOverlay';
import { compositionConfig as VibeTitleConfig, VibeTitle } from './VibeTitle';

const compositions = [
  { id: CaptionOverlayConfig.id || 'CaptionOverlay', Component: CaptionOverlay, config: CaptionOverlayConfig },
  { id: GlassSplitConfig.id || 'GlassSplit', Component: GlassSplit, config: GlassSplitConfig },
  { id: SplitLayoutConfig.id || 'SplitLayout', Component: SplitLayout, config: SplitLayoutConfig },
  { id: TitleOverlayConfig.id || 'TitleOverlay', Component: TitleOverlay, config: TitleOverlayConfig },
  { id: VibeTitleConfig.id || 'VibeTitle', Component: VibeTitle, config: VibeTitleConfig },
];

export const Root: React.FC = () => (
  <>
    {compositions.map(({ id, Component, config }) => (
      <Composition
        key={id}
        id={id}
        component={Component}
        durationInFrames={config.durationInFrames || 300}
        fps={config.fps || 30}
        width={config.width || 1920}
        height={config.height || 1080}
        defaultProps={config.defaultProps || {}}
        calculateMetadata={({ props }) => {
          const d = (props as any)?._durationFrames;
          return d ? { durationInFrames: d } : {};
        }}
      />
    ))}
  </>
);
